import type { NextPage } from "~types/next";

import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>GiNext</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>GiNext Boilerplate</h1>
    </div>
  );
};

export default Home;
